nominal:
  goal:
    coordinates:
      - 10.0
      - 10.0
      - 0.0
    control: 
      - 0.0
      - 9.81
    gain: 
      - [1.00, -0.00, 1.00, 0.00]
      - [-0.00, -200.00, -0.00, -28.8]
  frequency: 20.0